### ISSUE TITLE
tab/space standardization?

### ISSUE THREAD

**Issue by liakung1** [SD2E/synbiohub_adapter#13]
Hi all,

I'm new to the project and don't want to rock the boat but noticed that there's some files which use spaces and others that use tabs.  Would it be possible to standardize on one or the other?

In the synbiohub_adapter directory:

    SynBioHubUtil.py  tabs
    cache_query.py  spaces
    elastic.py   spaces
    fetch_SPARQL.py  spaces
    query_synbiohub.py  tabs

If I had a vote, I would vote for spaces, but I think standardization on either would be helpful.

Thanks,
Li Kung

**Comment by mwes** [comment]
Thanks @liakung1. Spaces has my vote, too.

**Comment by tcmitchell** [comment]
The [Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/) says [spaces are the preferred indentation method](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces).
