### ISSUE TITLE
No module named 'sbol'

### ISSUE THREAD

**Issue by mdehavensift** [SD2E/synbiohub_adapter#3]
How does one install the sbol module?

When trying to import query_synbiohub, I get the following error:

```
import synbiohub_adapter.query_synbiohub
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-8f825021a5cc> in <module>()
----> 1 import synbiohub_adapter.query_synbiohub

~/ves/gen3/lib/python3.6/site-packages/sbh_adapter-0.0.1-py3.6.egg/synbiohub_adapter/query_synbiohub.py in <module>()
      3 
      4 from .fetch_SPARQL import fetch_SPARQL
----> 5 from sbol import *
      6 
      7 ''' 

ModuleNotFoundError: No module named 'sbol'
```

I'm not sure where sbol comes from.

**Comment by mwes** [comment]
@mdehavensift try installing pySBOL? If you're running on OSX, it should pick up a recent install. We have a custom python 3.5 Ubuntu wheel we are testing here: https://github.com/SD2E/synbiohub_adapter/pull/2 We're close to getting 3.6 to work there, too, which is the targeted python version that Nic and company develop with.

**Comment by mdehavensift** [comment]
Thanks @mwes 

I'm on a linux machine. I was trying to setup with python3, but `pip install pySBOL` doesn't seem to work for me when using python3. It can't find that module. I switched to python2, and it was able to find that module.

Once it is installed however, it ran into problems with libsbol. But I think that's a known issue that Tom Mitchell is working on, right, libsbol not working on linux?

**Comment by mwes** [comment]
Yep, confirm the libsbol issue. Can you try this? it's a custom version Tom built for Ubuntu:
`pip3 install https://github.com/tcmitchell/pySBOL/blob/ubuntu/Ubuntu_16.04_64_3/dist/pySBOL-2.3.0.post11-cp35-none-any.whl?raw=true`
Tom is working on a 3.6 build. Thanks!

**Comment by mwes** [comment]
@mdehavensift Python 3.6 custom wheel: https://github.com/tcmitchell/pySBOL/blob/ubuntu/Ubuntu_16.04_64_3/dist/pySBOL-2.3.0.post11-cp36-none-any.whl?raw=true

**Comment by mdehavensift** [comment]
Closing this issue since the wheel file works for Ubuntu 16
