### ISSUE TITLE
Add a wrapped query for a strain's circuit

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#36]
I am currently issuing a SPARQL query to get the circuit type from a given strain in SBH:

https://gitlab.sd2e.org/sd2program/etl-pipeline-support/blob/develop/formats/common.py#L220

query = """PREFIX sbol: <http://sbols.org/v2#>
select distinct ?o where {{ <{}> <http://sbols.org/v2#role> ?o }}""".format(strain)

example input: https://hub.sd2e.org/user/sd2e/design/UWBF_7373/1
example output: http://www.openmath.org/cd/logic1#and

From which we parse "and". I would prefer to use a first-class SBHA query. When this is available, I will replace the calling code with this query. We have an authenticated SBHA already baked into the reactor base image. Thanks!

**Comment by bbartley** [comment]
@mwes Hi Mark, will this work for you?
```
>>> from synbiohub_adapter import *
>>> q = SynBioHubQuery(endpoint_url)
>>> hits = q.query_gate_logic(['https://hub.sd2e.org/user/sd2e/design/UWBF_7373/1', 'https://hub.sd2e.org/user/sd2e/design/UWBF_6389/1'], pretty=True) 
>>> for hit in hits:
...     print(hit)
... 
{'gate': 'https://hub.sd2e.org/user/sd2e/design/UWBF_7373/1', 'gate_type': 'http://www.openmath.org/cd/logic1#and'}
{'gate': 'https://hub.sd2e.org/user/sd2e/design/UWBF_6389/1', 'gate_type': 'http://www.openmath.org/cd/logic1#nor'}
```

**Comment by mwes** [comment]
@bbartley great - thanks! I will adjust to this and Nic's query and resolve both issues today.

**Comment by mwes** [comment]
https://gitlab.sd2e.org/sd2program/etl-pipeline-support/merge_requests/32 makes use of this - appears to work as expected. Thanks Bryan!
