### ISSUE TITLE
Add a wrapped query for a strain's input state

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#37]
I am currently issuing a SPARQL query to get the circuit type from a given strain in SBH:

https://gitlab.sd2e.org/sd2program/etl-pipeline-support/blob/develop/formats/common.py#L237

query = """
select distinct ?o where {{ <{}> <http://purl.org/dc/terms/title> ?o }}""".format(strain)

example input: https://hub.sd2e.org/user/sd2e/design/UWBF_7373/1
example output: UWBF_AND_10
From which we parse "10". This is obviously sub-optimal. Is there a better way to represent the input state the circuit is using? 

I would prefer to use a first-class SBHA query. When this is available, I will replace the calling code with this query. We have an authenticated SBHA already baked into the reactor base image. Thanks!

**Comment by nroehner** [comment]
I just added a wrapped version of the query that I originally shared with Dan. The method is named "query_gate_input_levels". Please give it a whirl and let me know what you think. I haven't added any additional formatting options yet.

**Comment by mwes** [comment]
@nroehner thanks - finally working on integrating this. Is the idea that I can concatenate the input levels provided here?
```
python tests/Test_SPARQLQueries.py TestSBHQueries.test_query_gate_input_levels
{'head': {'link': [], 'vars': ['gate', 'gate_type', 'input', 'level']}, 'results': {'distinct': False, 'ordered': True, 'bindings': [{'gate': {'type': 'uri', 'value': 'https://hub.sd2e.org/user/sd2e/design/UWBF_7373/1'}, 'gate_type': {'type': 'uri', 'value': 'http://www.openmath.org/cd/logic1#and'}, 'input': {'type': 'literal', 'value': 'pADH1:RGR-r2'}, 'level': {'type': 'literal', 'value': '1'}}, {'gate': {'type': 'uri', 'value': 'https://hub.sd2e.org/user/sd2e/design/UWBF_7373/1'}, 'gate_type': {'type': 'uri', 'value': 'http://www.openmath.org/cd/logic1#and'}, 'input': {'type': 'literal', 'value': 'pGRR-r5:RGR-r1'}, 'level': {'type': 'literal', 'value': '0'}}]}}
```

**Comment by mwes** [comment]
https://gitlab.sd2e.org/sd2program/etl-pipeline-support/merge_requests/32 makes use of this - appears to work as expected. Thanks Nic!

**Comment by nroehner** [comment]
Yes, you can concatenate the input levels, but I don't think the order in which they appear is necessarily conserved, so you might also want to consider the input IDs when deciding how to order the different input combinations for a particular type of gate. In your example, these are pADH1:RGR-r2 and  pGRR-r5:RGR-r1, so you might choose to put the level for pADH1:RGR-r2 first and the level for pGRR-r5:RGR-r1 second for all the AND gate strains.

**Comment by nroehner** [comment]
I'm not sure if there were canonical orderings for each gate type (i.e. pADH1:RGR-r2 before pGRR-r5:RGR-r1 for all AND strains), but I don't think it should matter so long as we pick one ordering and are consistent in applying it for all gate strains of a particular type.

**Comment by mwes** [comment]
Do you have a suggestion for how to encode this? Currently I am running:
```
input_state_bindings = sbh_query.query_gate_input_levels([strain])['results']['bindings']
input_state = "".join(binding["level"]["value"] for binding in input_state_bindings)
```
