### ISSUE TITLE
query_gate_input_levels output ordering issues

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#43]
Lab trace conversion code makes use of two SBHA functions:

1) query_designs_by_lab_ids: to retrieve a SBH URI for a given internal lab id (from the program dictionary)
then
2) query_gate_input_levels for a given SBH, to look up its input levels

The combined output across these two functions will look like the following:

```
"strain": {
    "sbh_uri": "https://hub.sd2e.org/user/sd2e/design/UWBF_6389/1", <-- SBH URI, from query_designs_by_lab_ids
    "label": "UWBF_NOR_10", <-- SBH URI Label, from query_designs_by_lab_ids
    "circuit": "NOR",
    "input_state": "10", <-- from query_gate_input_levels
    "lab_id": "name.transcriptic.6389" <-- internal id here is "6389"
},
```

The converter reads the input state according the ordering of the bindings returned from the query_gate_input_levels query. This input state appears to be inconsistent for some strains when compared to the URI label. Can some guidance or ordering/other metadata be provided so we can retrieve a correct input_state value? 

Related discussion here: https://github.com/SD2E/synbiohub_adapter/issues/37

This worked consistently previously, but we were likely just getting lucky - new strains have caused this issue to re-emerge when looking closely at the outputs.

Here are two examples:

Lab: Transcriptic
Lab ID: 6389
Returns: Correct input state for UWBF_NOR_10 strain ("10")

URI query: https://gist.github.com/mwes/955b8e9d11af25f97e0c8378cb0d8a6e
Input state query: https://gist.github.com/mwes/a208defdae4dd48d138dd63028b20f4a

Lab: Biofab
Lab ID: 16969
Return: Incorrect input state for "UWBF_XOR_01" strain ("10")

URI query: https://gist.github.com/mwes/95e5dd20978215aeb0bf8aaa0b0e5166
Input state query: https://gist.github.com/mwes/aab367b516537f84ca4312e5ca18ed7d

**Comment by jakebeal** [comment]
Can we reconsider using the canonical ordering suggestion that I had made before, in which inputs are sorted by their identifiers (e.g., lexicographically)?  This sort of issue is what it was intended to deal with.

**Comment by mwes** [comment]
Sure, if that will work. I don’t have a strong opinion on how this is implemented. The requirement is that the computer interpretable input_levels function return from SBHA matches the human-interpretable label. I’m not doing any special interpretation after I call the function, so the expectation is that this will be handled within the adapter.

**Comment by mwes** [comment]
From the discussion at the Data Representation scrum Tuesday, November 7, 2 PM EST we determined a path forward:
- Input levels will be sorted by the SynbioHub Adapter using consistent lexicographic ordering.
- Any discrepancies noted in the label URIs will be manually corrected (00 and 11 states will not need changes, obviously).

**Comment by nroehner** [comment]
The following commit adds lexicographic ordering to query_gate_input_levels when it is called for a single gate:

0194bad518e7ede7a615889291aa790ac4979407

**Comment by mwes** [comment]
Confirm fixed.
