### ISSUE TITLE
Request for SBHA to retry SPARQL Queries

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#51]
Can we have SBHA retry SPARQL queries in case of connectivity or other (potentially non-deterministic) issues? Some sort of max-retry, as well as backoff is likely a good idea so we don't retry-hug ourselves to death. Here is an example failure trace from the perspective of the caller calling 
`query_designs_by_lab_ids`

Let me know if you would like more information. 

```
designs = sbh_query.query_designs_by_lab_ids(sbh_lab, [id_to_map], verbose=True)
  File "/usr/local/lib/python3.6/dist-packages/synbiohub_adapter/query_synbiohub.py", line 1034, in query_designs_by_lab_ids
    design_query_result = self.fetch_SPARQL(self._server, design_query)
  File "/usr/local/lib/python3.6/dist-packages/synbiohub_adapter/fetch_SPARQL.py", line 9, in fetch_SPARQL
    results = sparql.query().convert()
  File "/usr/local/lib/python3.6/dist-packages/SPARQLWrapper/Wrapper.py", line 798, in query
    return QueryResult(self._query())
  File "/usr/local/lib/python3.6/dist-packages/SPARQLWrapper/Wrapper.py", line 766, in _query
    response = urlopener(request)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
```

**Comment by tcmitchell** [comment]
TACC's [bacanora](https://github.com/SD2E/bacanora) uses [tenacity](https://github.com/jd/tenacity) for retrying calls. It seems like that would be a good fit here.

Some questions:

* Is there a repeatable test case that can help determine the accuracy of an enhancement?
* Is there a range of synbiohub_adapter methods where this should be implemented? Or just in `fetch_SPARQL()`?
* Are there certain exceptions that indicate a retry vs. other errors that indicate a terminal failure?

**Comment by mwes** [comment]
Thanks, Tom.

Tenacity seems like a good choice.

1) This issue was filed in relation to a new SBH deploy that was non-deterministically failing  on certain queries. This was believed to be due to load issues on the host. TACC made some improvements to the hosts resources and the the issue "went away", but this doesn't mean that under some conditions SBH will fail on certain queries. A heavy load test that performs multi-threaded querying might help reproduce this. The failures we were seeing were both in dictionary reads/writes as well as lab trace conversion functions that called through the SBHA.

2) Suggest this should be implemented at the lowest level where this is failing that is common to the queries, e.g `fetch_SPARQL()`. The method being called did not have an affect on the failure condition.

3) Suggest some maximum number of retries be performed, after which we can declare a failure vs. a transient load or connection error.
