### ISSUE TITLE
Get Password for Query Tests from Environment Variable

### ISSUE THREAD

**Issue by nroehner** [SD2E/synbiohub_adapter#54]
Now that all queries use the secure SynBioHub SPARQL endpoint, our tests need to supply a legitimate username and password. Currently, the username is hardcoded in the tests and the password is obtained from the user using getpass, but these should probably both be obtained from appropriate environment variables.

**Comment by bbartley** [comment]
Implemented in fbcf46911ead092458b30c95833262ba18067f8b
