### ISSUE TITLE
synbiohub_adapter dictionary write support

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#59]
synbiohub_adapter currently supports reading dictionary values that are stored in SBH through the function call `query_designs_by_lab_ids` https://github.com/SD2E/synbiohub_adapter/blob/master/synbiohub_adapter/query_synbiohub.py#L1087

This function allows pythonic consumers of SBH to easily check if a mapping is available in SBH (mediated through the dictionary). It would be extremely useful to allow for an equivalent operation to performs writes to the dictionary. I can think of at least two current users that would make use of this as soon as it was available. Until such a function is available, all possible dictionary updates have to be made manually to the Google Sheet. As a suggested timeline, sometime in the next 2-4 weeks would be superb if resources and priorities could be allocated for this.

Example users:

TA4: Programmatically submits entries to the "mapping failures" tab in real-time as new traces are converted. Populating these entries in the dictionary is currently a manual process. Interested point(s) of contact: @mwes.

TA3: Programmatically submit mapping entries to the "Strains" and "Reagents" tabs in real-time as lab traces are created or uploaded. Populating these entries in the dictionary is currently a manual process. Interested point(s) of contact: @bjkeller @mwes. 

The synbiohub_adapter should take care of any relevant authentication. Reactors that have the SBHA already bundled can have credentials provided. Users of the adapter should not need to know whether they are writing to a Google Sheet and/or SBH, or to have to deconflict between the two. 

A common error case that should be handled is submitting a strain mapping, a reagent mapping, or a mapping failures entry when one such entry already exists in the dictionary. We should not create a duplicate entry for these submissions to the dictionary or SBH, but return some kind of (recoverable) error or return state to the caller.

**Comment by dsumorok-raytheon** [comment]
This work will be done in the SD2-Librarian repository.  The ticket has been moved to https://gitlab.sd2e.org/sd2program/SD2-Librarian/issues/72.

**Comment by mwes** [comment]
@dsumorok-raytheon can you clarify? To be clear, we're requesting python support through the synbiohub_adapter. Will https://gitlab.sd2e.org/sd2program/SD2-Librarian/issues/72 achieve that?

**Comment by dsumorok-raytheon** [comment]
We felt that, since this library wraps an interface to the spreadsheet, and by itself does not access synbiohub, this library fits better in the Librarian repository.  This library will still be a python library, and will be completely independent from the java-based Dictionary application.

**Comment by mwes** [comment]
Got it. Thanks!
