### ISSUE TITLE
Document lack of Python 2 compatibility

### ISSUE THREAD

**Issue by tcmitchell** [SD2E/synbiohub_adapter#83]
The code as it stands is not compatible with Python 2. It is easy to fix though.

How important is Python 2 compatibility?

* If it is important, verification of Python 2 compatibility should be built into the tests.
* If it is nice to have, let's make the change but not worry about verification. Or make a verification determination when making releases.
* If it is not important, or even undesirable, let's declare synbiohub_adapter to be compatible only with Python 3.

Here's the fix necessary to make synbiohub_adapter compatible with Python 2:

```diff
--- a/synbiohub_adapter/query_synbiohub.py
+++ b/synbiohub_adapter/query_synbiohub.py
@@ -11,14 +11,14 @@ from sbol import *
     author(s) : Nicholas Roehner
                 Tramy Nguyen
 '''
-class SynBioHubQuery(SBOLQuery):
+class SynBioHubQuery(SBOLQuery, object):
     ''' This class is used is used to push and pull information from SynBioHub.
         Each method of this class is a SPARQL query used to call to the specified instance of SynBioHub.
     '''
 
     # server: The SynBioHub server to call sparql queries on.
     def __init__(self, server, use_fallback_cache=False, user = None, authentication_key = None, spoofed_url = None):
-        super().__init__(server, use_fallback_cache, user, authentication_key, spoofed_url)
+        super(SynBioHubQuery, self).__init__(server, use_fallback_cache, user, authentication_key, spoofed_url)
 
     # Control query methods \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
 
```

**Comment by tcmitchell** [comment]
I'd like to hear feedback from at least 2 of @bbartley, @jakebeal, and @nroehner. @mwes is probably also an interested party and is encouraged to comment. Should anyone else be asked for input?

**Comment by tcmitchell** [comment]
Digging a little further, there are plenty of occurrences of `print()`, and occurrences of `from __future__ import print_function`. That leads me to believe that more of the code is incompatible with Python 2 and is simply not covered by the current set of unit tests.

Is there any objection to declaring the library incompatible with Python 2?

**Comment by jakebeal** [comment]
I seem to recall that something else may have already forced us to give up on Python 2 compatibility, but am not sure what it was.

**Comment by bbartley** [comment]
Hi all, since TACC environments primarily support Python 3, I would recommend consciously aiming to support Python 3.  I have often found myself working on development code for SD2 that has Python 2 and Python 3 conventions intermixed, and would like a clear guideline as well.

**Comment by mwes** [comment]
Yes - general SD2 program (and overall linux positioning) has to been to use python3 for all new work. I have no issues with declaring this python2 compatible.

**Comment by mwes** [comment]
@jakebeal you are probably thinking of this: https://sd2e.slack.com/archives/C5UF779PD/p1522088944000001

**Comment by tcmitchell** [comment]
> Yes - general SD2 program (and overall linux positioning) has to been to use python3 for all new work. I have no issues with declaring this python2 compatible.

@mwes did you mean _in_compatible? You have no issues with declaring this python2 _incompatible_?

**Comment by jakebeal** [comment]
I'm pretty sure that's what he meant.

**Comment by mwes** [comment]
Oh yes, my apologies.

**Comment by tcmitchell** [comment]
Resolving this issue is a matter of documentation. I don't think there is a rush to do so. Information about the lack of Python 2 compatibility can be added to [README.md](https://github.com/SD2E/synbiohub_adapter/blob/master/README.md)
