### ISSUE TITLE
Cannot install synbiohub_adapter on OSX

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#91]
pysbol issue?

```
pip install --process-dependency-links git+https://github.com/SD2E/synbiohub_adapter.git@v1.0
Collecting git+https://github.com/SD2E/synbiohub_adapter.git@v1.0
  Cloning https://github.com/SD2E/synbiohub_adapter.git (to v1.0) to /private/var/folders/h5/fmcqbqb523n22jsvrgwlqbwm0000gn/T/pip-rva4zgyp-build
  DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Collecting SPARQLWrapper>=1.8.2 (from synbiohub-adapter==1.0)
  Using cached https://files.pythonhosted.org/packages/7f/c3/72d2d0a2ad86bd8d2bc762406c838f479c421678161cf78585d085436919/SPARQLWrapper-1.8.2-py3-none-any.whl
Collecting appdirs>=1.4.3 (from synbiohub-adapter==1.0)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting pySBOLx==0.1 (from synbiohub-adapter==1.0)
  Cloning https://git@github.com/nroehner/pySBOLx.git to /private/var/folders/h5/fmcqbqb523n22jsvrgwlqbwm0000gn/T/pip-build-5nbuqf0r/pySBOLx
  DEPRECATION: Dependency Links processing has been deprecated and will be removed in a future release.
Collecting pycodestyle>=2.5.0 (from synbiohub-adapter==1.0)
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
Collecting pysbol==2.3.1.post6 (from synbiohub-adapter==1.0)
  Could not find a version that satisfies the requirement pysbol==2.3.1.post6 (from synbiohub-adapter==1.0) (from versions: 2.1.1.post0, 2.2.0.post2, 2.2.0.post3, 2.2.0.post4, 2.3.0.post0, 2.3.0.post1, 2.3.0.post5, 2.3.0.post6, 2.3.0.post7, 2.3.0.post8, 2.3.0.post9, 2.3.0.post10, 2.3.0.post11, 2.3.0.post12, 2.3.0.post15, 2.3.0.post16, 2.3.0.post17, 2.3.0.post18, 2.3.0.post19, 2.3.0.post20, 2.3.1.post0)
No matching distribution found for pysbol==2.3.1.post6 (from synbiohub-adapter==1.0)
```

**Comment by tcmitchell** [comment]
Hmmm. It just worked for me. What OS are you using? What version of Python3? What version of pip?

I'm on Ubuntu 18.04 (bionic). I'm using the stock Python 3.6.7.

Instead of running "pip3" (or in your case "pip"), I ran `python3 -m pip install ...`

I also see pySBOL 2.1.3.post6 on PyPI: https://pypi.org/project/pySBOL/#history

**Comment by mwes** [comment]
OSX, Python 3.6.4

**Comment by mwes** [comment]
That wheel only looks to have: ```cp36-none-manylinux1_x86_64```

**Comment by bbartley** [comment]
There's no post6 for MacOSX.  If installing on Mac, synbiohub_adapter should probably just default to installing the most recent wheel.  Linux wheels are a little more tricky, so these need to be tied to a specific post

**Comment by tcmitchell** [comment]
What if there is a change in one of the pysbol postX versions that is required for a new feature in synbiohub_adapter? I don't see a way to tell what has changed between the pysbol postX versions, is there an indicator somewhere? Like on the PyPI page? I don't see tags corresponding to these postX versions.

We could declare the dependency on pysbol to be "pysbol>=2.3.1", and get the latest postX available on a given platform. That feels dicey if synbiohub_adapter starts to rely on features implemented in a postX version that doesn't happen to be supported on various platforms.

You'll see the rationale for pinning a specific version of pysbol in PR #78. That can be changed if we can agree on the minimum version synbiohub_adapter actually requires.

**Comment by tcmitchell** [comment]
The most recent version of pySBOL that is compatible with both Linux (specifically x86_64 Ubuntu 18.04) and macOS is "2.3.0.post12". I will try to install that and see if the tests pass. Is that the version we should standardize on?

If not, we know for sure that Mac users and Linux users will be using different versions of pySBOL, which seems like a recipe for problems.

**Comment by tcmitchell** [comment]
2.3.0 lacks authentication. It's a non-starter. @bbartley please advise.

**Comment by mwes** [comment]
I agree on normalizing on the same pySBOL version

**Comment by bbartley** [comment]
Normalizing on the same version is fine (2.3.1), but it is not advisable to normalize on the same post across different platforms.  It's probably kludgey, but the setup.py script can be tailored to install different posts conditionally depending on which platform.

**Comment by mwes** [comment]
@bbartley curious - why is not advisable to normalize on the same post across different platforms?  I don't know how your release process works. Is there behavior in those releases that is platform specific?

**Comment by tcmitchell** [comment]
We can specify the dependency as "pysbol>=2.3.1" so that each platform gets the latest .postX version for that platform. @bbartley are you saying there are no substantive code changes between the various postX versions of the pySBOL package? If that's the case, I'm comfortable with the "pysbol>=2.3.1" dependency.

**Comment by bbartley** [comment]
One of the big differences between Linux posts is the underlying build configuration, not the source code.  There's customization that I have to do, depending on which Linux system I'm targeting.  So, 2.3.1post1 and 2.3.6post6 have the same underlying source, but one works on Ubuntu and the other one works on CentOS.  I think the source on these is essentially the same as 2.3.0post0 for Mac.

Another issue is that it's very difficult for me to generate new wheels for Mac OSX, Linux, and Windows concurrently.  So I might generate several new posts on MacOSX for hotfixes, but never release equivalent posts on the other platforms.

It's anarchy, I know.

**Comment by tcmitchell** [comment]
I think the proper resolution to this is to change the dependency to `pysbol>=2.3.1`. Having now read the [description of post releases](https://www.python.org/dev/peps/pep-0440/#post-releases), that seems like a reasonable way to go.

I do detect a code difference between 2.3.1.post0 and 2.3.1.post6. It's minor, and may be related to the underlying build.

I also see commits in the 2.3.1 releases of pySBOL that do not appear on GitHub. I find that concerning, but it's not mine to fix.
