### ISSUE TITLE
synbiohub_adapter install breaks on latest pip (19.0.3)

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#92]
Well, they did warn it was deprecated! Suggestions? Is there a frozen pip version I should target? Or could we update the install to work on newer pip versions?

```
pip install --process-dependency-links git+https://github.com/SD2E/synbiohub_adapter.git@v1.0

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --process-dependency-links
```

**Comment by tcmitchell** [comment]
For now, please use something like pip 9.0.1. In #91 you indicated you were using pip 9.0.3, which should be fine.

Meanwhile, I'll take a look at getting something compatible with more recent pips. This may require @nroehner's queryDNA branch that he says removes the dependency on [pySBOLx](https://github.com/nroehner/pySBOLx) which is the dependency link in `setup.py`.

**Comment by mwes** [comment]
Confirm pip 9.0.3 works fine. This solution work fine for me for now; TACC builds also freeze their pip version to this. So a lower priority on this, but eventually will need to be address if anyone upgrade their pip.
